/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services/website-development'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesSaasApplicationsRouteImport } from './routes/services/saas-applications'
import { Route as ServicesErpSystemsRouteImport } from './routes/services/erp-systems'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services/digital-marketing'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services/app-development'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/services/website-development',
    path: '/services/website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSaasApplicationsRoute =
  ServicesSaasApplicationsRouteImport.update({
    id: '/services/saas-applications',
    path: '/services/saas-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesErpSystemsRoute = ServicesErpSystemsRouteImport.update({
  id: '/services/erp-systems',
  path: '/services/erp-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/services/digital-marketing',
    path: '/services/digital-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/services/app-development',
  path: '/services/app-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-systems': typeof ServicesErpSystemsRoute
  '/services/saas-applications': typeof ServicesSaasApplicationsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-systems': typeof ServicesErpSystemsRoute
  '/services/saas-applications': typeof ServicesSaasApplicationsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-systems': typeof ServicesErpSystemsRoute
  '/services/saas-applications': typeof ServicesSaasApplicationsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/services/app-development'
    | '/services/digital-marketing'
    | '/services/erp-systems'
    | '/services/saas-applications'
    | '/services/seo'
    | '/services/website-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/services/app-development'
    | '/services/digital-marketing'
    | '/services/erp-systems'
    | '/services/saas-applications'
    | '/services/seo'
    | '/services/website-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/services/app-development'
    | '/services/digital-marketing'
    | '/services/erp-systems'
    | '/services/saas-applications'
    | '/services/seo'
    | '/services/website-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesErpSystemsRoute: typeof ServicesErpSystemsRoute
  ServicesSaasApplicationsRoute: typeof ServicesSaasApplicationsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/services/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/saas-applications': {
      id: '/services/saas-applications'
      path: '/services/saas-applications'
      fullPath: '/services/saas-applications'
      preLoaderRoute: typeof ServicesSaasApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/erp-systems': {
      id: '/services/erp-systems'
      path: '/services/erp-systems'
      fullPath: '/services/erp-systems'
      preLoaderRoute: typeof ServicesErpSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/services/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/services/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesErpSystemsRoute: ServicesErpSystemsRoute,
  ServicesSaasApplicationsRoute: ServicesSaasApplicationsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
